<?php
return [
    [
        "user_id" => 13,
        "name" => "Margherita",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 5.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella  e basilico",
        "description" => "La Margherita, il classico Napoletano",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Marinara",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 4.00,
        "ingredients" => "Farina di grano duro, pomodoro, aglio e origano",
        "description" => "Meno di così è solo impasto",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Bufalina",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella di bufala e basilico",
        "description" => "Più sfiziosa di una Margherita",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Verdure",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, verdure grigliate",
        "description" => "Per sentirsi meno in colpa",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Diavola",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.50,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, salamino piccante, olive nere",
        "description" => "Gustosa, quasi troppo",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "San Daniele",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 8.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, prosciutto San Daniele",
        "description" => "Il crudo non lo mettiamo in forno",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Capricciosa",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 8.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, prosciutto cotto, funghi, olive verdi e nere, e carciofini",
        "description" => "Intensa",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Bismark",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 8.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, prosciutto cotto, uova",
        "description" => "L'uovo con o senza guscio?",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Mare",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 9.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, frutti di mare",
        "description" => "Non mi sembrano frutti",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Cotto",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 7.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, prosciutto cotto",
        "description" => "Inoffensiva",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Tonno e Cipolle",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 7.50,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, tonno e cipolle",
        "description" => "No pinne gialle",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Pancetta e Ragù",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 8.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, pancetta, ragù",
        "description" => "Coraggiosa",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "CocaCola",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Sprite",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Fanta",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 13,
        "name" => "Acqua",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 1.00,
        "ingredients" => "-",
        "description" => "50cl",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Cotto e Fontina",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 5.00,
        "ingredients" => "Prosciutto cotto, fontina",
        "description" => "Carattere mite",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Crudo e Mozzarella",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.00,
        "ingredients" => "Prosciutto crudo, mozzarella",
        "description" => "Avvolgente",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Squacquerone e Rucola",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 5.00,
        "ingredients" => "Squacquerone, rucola",
        "description" => "Un classico vegetariano",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Speck e Brie",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.00,
        "ingredients" => "Speck, brie",
        "description" => "Sapore alpino",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Diavola",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.50,
        "ingredients" => "Salame piccante, provola",
        "description" => "Impegnativa",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Bresaola e Rucola",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 7.00,
        "ingredients" => "Bresaola, rucola",
        "description" => "Leggera",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Mozzarella e Pomodorini",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 5.00,
        "ingredients" => "Mozzarella, pomodorini",
        "description" => "Sapore Mediterraneo",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Gamberetti e Zucchine",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 8.00,
        "ingredients" => "Gamberetti, zucchine, salsa rosa",
        "description" => "Sfiziosa",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Spincai e Ricotta",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 6.00,
        "ingredients" => "Spinaci, ricotta",
        "description" => "Come i cannelloni",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Culatello",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 8.00,
        "ingredients" => "Culatello",
        "description" => "Raffinata",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Cotto e Insalata",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 6.50,
        "ingredients" => "Prossciutto cotto, lattuga",
        "description" => "Anonima",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Nutella",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 5.00,
        "ingredients" => "Nutella",
        "description" => "Un dolce travestito",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "CocaCola",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Sprite",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Fanta",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 14,
        "name" => "Acqua",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 1.00,
        "ingredients" => "-",
        "description" => "50cl",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Margherita",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 5.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella  e basilico",
        "description" => "La Margherita, il classico Napoletano",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Marinara",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 4.00,
        "ingredients" => "Farina di grano duro, pomodoro, aglio e origano",
        "description" => "Meno di così è solo impasto",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Bufalina",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella di bufala e basilico",
        "description" => "Più sfiziosa di una Margherita",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Verdure",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, verdure grigliate",
        "description" => "Per sentirsi meno in colpa",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Diavola",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 6.50,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, salamino piccante, olive nere",
        "description" => "Gustosa, quasi troppo",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "San Daniele",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 8.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, prosciutto San Daniele",
        "description" => "Il crudo non lo mettiamo in forno",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Capricciosa",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 8.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, prosciutto cotto, funghi, olive verdi e nere, e carciofini",
        "description" => "Intensa",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Bismark",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 8.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, prosciutto cotto, uova",
        "description" => "L'uovo con o senza guscio?",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Mare",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 9.00,
        "ingredients" => "Farina di grano duro, pomodoro, mozzarella, frutti di mare",
        "description" => "Non mi sembrano frutti",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Patatine Fritte",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 3.00,
        "ingredients" => "Patate",
        "description" => "Snack gustoso",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Panino Kebab",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 7.50,
        "ingredients" => "Carni varie, insalata, pomodori, cipolla, salsa piccante",
        "description" => "Perfetto a mezzanotte",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Panino Falafel",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 4.00,
        "ingredients" => "Polpette di ceci, insalata, pomodori, salsa yougurt",
        "description" => "Se non vuoi il kebab",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "CocaCola",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Sprite",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Fanta",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 15,
        "name" => "Acqua",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 1.00,
        "ingredients" => "-",
        "description" => "50cl",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Leggera",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 8.00,
        "ingredients" => "Riso, quinoa, edamame, mango, radicchio",
        "description" => "Carattere mite",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Vegan",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 8.00,
        "ingredients" => "Riso, quinoa, cipolle croccanti, edamame, arachidi",
        "description" => "Cruelty free",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Marina",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 9.00,
        "ingredients" => "Riso, quinoa, mango, edamame, salmone",
        "description" => "Delicata",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Workout",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 8.00,
        "ingredients" => "Riso, quinoa, pollo, lenticchie, noci",
        "description" => "Concentrato di proteine",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Golosa",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 8.50,
        "ingredients" => "Riso, quinoa, cipolle croccanti, edamame, arachidi, tonno, mango",
        "description" => "Piacere in bowl",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Mini",
        "img" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
        "price" => 5.00,
        "ingredients" => "Riso, quinoa, cipolle croccanti, edamame, arachidi",
        "description" => "Per chi ha poco tempo",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Mediterranea",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 5.00,
        "ingredients" => "Riso, pomodorini, mozzarella, basilico",
        "description" => "Sapore Mediterraneo",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Marina",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 9.00,
        "ingredients" => "Riso, tonno, alga nori, salmone, gamberetti",
        "description" => "Sfiziosa",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Cannellona",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 7.00,
        "ingredients" => "Riso, spinaci, ricotta",
        "description" => "Come i cannelloni",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Morbida",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 8.00,
        "ingredients" => "Riso, stracchino, mango, avocado",
        "description" => "Cremosa",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Spicy",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 6.50,
        "ingredients" => "Riso, peproncini a fette, ceci, paprika",
        "description" => "Decisa",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Dessert",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 5.00,
        "ingredients" => "Riso, crema di mango, arachidi caramellate",
        "description" => "Un dolce travestito",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "CocaCola",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Sprite",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Fanta",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 2.00,
        "ingredients" => "-",
        "description" => "33cl",
        "visibility" => true,
    ],
    [
        "user_id" => 16,
        "name" => "Acqua",
        "img" => "https://2.bp.blogspot.com/-VpO0bvEuQX8/XB9T6wFGr8I/AAAAAAAANzo/z-ooYWHvK2EHUPJmVt7-4CugQjDqpOW3gCLcBGAs/s1600/IMG_2342.JPG",
        "price" => 1.00,
        "ingredients" => "-",
        "description" => "50cl",
        "visibility" => true,
    ],

];
